FROM node:14.15.0-alpine3.10 as builder

WORKDIR /app

RUN apk add --no-cache python make g++;

COPY src/back-end/yarn.lock src/back-end/package.json /app/

RUN yarn global add @nestjs/cli;
RUN yarn install;

COPY src/back-end /app

RUN yarn build;

EXPOSE 80
CMD ["node", "dist/main"]
