version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - dev.env
    volumes:
      - './src/front-end/:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - api
    restart: on-failure
    stdin_open: true
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    env_file:
      - dev.env
    volumes:
      - './src/back-end/:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    depends_on:
      - database
    restart: on-failure
    stdin_open: true
  database:
    image: mongo:4.4.2-bionic
    env_file: dev.env
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - '27017:27017'
    restart: on-failure
    stdin_open: true

