version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - dev.env
    volumes:
      - './src/front-end/:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - api
    stdin_open: true
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    env_file:
      - dev.env
    environment:
      API_DATABASE_HOST: database
    volumes:
      - './src/back-end/:/app'
      - '/app/node_modules'
    ports:
      - '4000:4000'
    depends_on:
      - database
    stdin_open: true
  database:
    image: mongo:4.4.2-bionic
    restart: unless-stopped
    env_file: dev.env
